.import __player_collide
.import __player_dirto
.import __player_harm
.import __player_init
.import __player_off
.import __player_on
.import __player_update
.import __player_xpos
.import __player_ypos

.scope player
	collide = __player_collide
	dirto = __player_dirto
	harm = __player_harm
	init = __player_init
	on = __player_on
	off = __player_off
	update = __player_update
	xpos = __player_xpos
	ypos = __player_ypos
.endscope
